---
title: "RREMseq_CustomFunctions.R"
author: "Iris Liu"
date: "2025-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


## Calculate CpG coverage using Seqmonk CpG probes (Read position Probe Generator; minimum read count per position=1)
```{r}
UniqueCpG_Seqmonk = function(methylation_call, SampleStart = NA, cov = NA)
{
  library(dplyr)
  library(data.table)
  library(tidyverse)
  
  Sample_fil = as.data.frame(methylation_call$Start)
  EndCol = ncol(methylation_call)
  SampleData = methylation_call[,SampleStart:EndCol]
  Sample_fil = cbind(Sample_fil, SampleData)
  all_sample = as.list(SampleStart:EndCol)
  SampleEnd = ncol(Sample_fil)
  SampleName = colnames(Sample_fil[2:SampleEnd])
  
  uniqueCpG = lapply(all_sample, function(comp){
    totalCpG =  length(na.omit(methylation_call[,comp]))
    methylation_call_fil = methylation_call[!is.na(methylation_call[,comp]), ]
    sample_position = as.data.frame(methylation_call_fil$Start)
    Sample_CpGdup = CountCpGduplicate(sample_position[,1]) 
    dupCpG_num = length(Sample_CpGdup$duplicatedCount)
    uniqueCpG = totalCpG - dupCpG_num
    return(uniqueCpG)
  })
  
  names(uniqueCpG) <- SampleName
  
  uniqueCpG.df <- uniqueCpG %>%
    as.data.frame() %>%
    t() %>%
    as.data.frame() %>%
    tibble::rownames_to_column(var = "Sample")
  
  colnames(uniqueCpG.df) = c("Sample", "UniqueCpGs")
  
  
  uniqueCpG.df$cov = cov
  output = uniqueCpG.df
  return(output)
}

```


## Calculate duplicated CpG numbder
```{r}
CountCpGduplicate <- function(x){
  
  y <- as.data.frame(x)
  
  count.occurances <- 0
  row_odd <- seq_len(nrow(y)) %% 2
  y.row <- row.names(y)
  num.odd <-as.numeric(y.row[row_odd==0])
  N <- length(num.odd)
  
  z <- lapply(num.odd, function(i) {
    a <- x[i]
    b <- x[i-1]
    c <- x[i+1]
    if (isTRUE(a-b == 1)| (isTRUE(c-a == 1) )){
    count.occurances = count.occurances + 1
      
    }
  })
  z.fil <- z[!sapply(z,is.null)]
  list(duplicatedCount = z.fil)
}


```


## Calculate genomic elements coverage from Seqmonk data
```{r}
FeatureCount <- function(df,TotalFeature,Cov) {
  counts <- colSums(!is.na(df))
  result <- data.frame(Sample = names(counts), Non_NA_Count = counts)
  result <- extract_before_underscore(result, "Sample", "Group")
  result$percentage <- result$Non_NA_Count/TotalFeature
  result$Cov <- Cov
  return(result)
}
```



## Extract methylation coverage within TregSE
```{r}
FilTregSE = function(CovFile, TregSE,ExportName)
{
  library(dplyr)
  library(data.table)
  library(tidyverse)
  
  
  cov <- CovFile
  
  probe <- paste(cov[,1], cov[,2], sep = ":")
  probe <- paste(probe, cov[,2], sep = "-")
  probe <- as.data.frame(probe)
  probe <- mutate_all(probe, funs(gsub("chr", "Chr", .)))
  cov.location <- cbind(probe,cov)
  
  TregSE.cov <- merge(cov.location,
                      TregSE,
                      by.x = "probe",
                      by.y = "Probe", all = F)
  TregSE.cov.export <- TregSE.cov[,2:7]
  
  write.table(TregSE.cov.export, file = ExportName, sep = "\t", row.names = F, col.names = F,quote = F)
  return(TregSE.cov.export)
}

```

## Calculate genomic elements methylation status 
```{r}

#calculate average genomic elements methylation status 
get_FeatureBeta_mean <- function(FeatureMethyl, position){
  FeatureMethyl_mean = apply(FeatureMethyl, 1, mean)
  FeatureMethyl_mean = na.omit(FeatureMethyl_mean)
  return(FeatureMethyl_mean)
}

#calculate the range of genomic elements methylation status 
get_FeatureBeta_range <- function(FeatureMethyl, position){

  FeatureMethyl_max <- apply(FeatureMethyl, 1, max)
  FeatureMethyl_min <- apply(FeatureMethyl, 1, min)
  FeatureMethyl_range <- cbind(FeatureMethyl_min,FeatureMethyl_max)
  colnames(FeatureMethyl_range) <- c("min", "max")
  FeatureMethyl_range <- as.data.frame(FeatureMethyl_range)
  return(FeatureMethyl_range)
}
```

